name: Deploy para GitHub Pages

on:
  push:
    branches: [main]  # Roda esse workflow quando houver push na branch main

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest  # Sistema que o GitHub vai usar

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  # Baixa o código do repositório

      - name: Verificar existência do index.html
        run: |
          if [ ! -f public/index.html ]; then
            echo 'Arquivo index.html não encontrado!'
            exit 1
          fi

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
